baseURL = "https://wesshaddix.com"
title = "Wes Shaddix"
copyright = "Copyright © 2020, Wes Shaddix; all rights reserved."
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-587905-4"
DisqusShortname = "wesshaddix"
theme = "hugo-theme-chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Wes Shaddix"
  description = "It's just me."
  homepageImage = "/images/homepage-image.jpg"
  share = true
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = true
    email = "wes.shaddix@outlook.com"
    facebook = "https://www.facebook.com/wes.shaddix.3/"
    twitter = "https://twitter.com/wshaddix"
    #linkedin = "https://linkedin.com"
    #stack-overflow = "https://stackoverflow.com"
    instagram = "https://www.instagram.com/wes.shaddix/"
    github = "https://github.com/wshaddix"
    #weibo = "https://www.weibo.com"
    #medium = "https://medium.com"
    #pinterest = "https://pinterest.com"
    #reddit = "https://reddit.com"
    #gitlab = "https://gitlab.com"
    #mastodon = "https://mastodon.social"
    #keybase = "https://keybase.io/"

  [params.prismJS]
    enable = true
    #theme = "okaidia"
    theme = "tomorrow"

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
