baseURL = "http://www.wshaddix.com"
languageCode = "en-us"
title = "Wes Shaddix"
PygmentsCodeFences = true
publishDir = "docs"
author = "Wes Shaddix"
theme = "code-editor"

[params]
    author = "Wes Shaddix"
    locale = "en-US"
    # rootlink = "/"
    # rootlink specifies where Root in menu.html links to. If it's not set then baseurl will be used.